// AUTO-GENERATED — do not edit; run: npm run gen:perm (ba-backend)
/** Profile: central — aligned with access/catalog.js */

export const PERM = {
	home: { module: "system.home" },
	equipment: {
		module: "system.equipment_management",
		deviceCreate: "system.equipment_management.device.create",
		deviceUpdate: "system.equipment_management.device.update",
		deviceDelete: "system.equipment_management.device.delete",
	},
	personnel: {
		module: "system.personnel",
		groupCreate: "system.personnel.group.create",
		groupUpdate: "system.personnel.group.update",
		groupDelete: "system.personnel.group.delete",
		personCreate: "system.personnel.person.create",
		personUpdate: "system.personnel.person.update",
		personDelete: "system.personnel.person.delete",
		deviceSync: "system.personnel.device_sync",
		syncEdit: "system.personnel.sync.edit",
	},
	alertLog: {
		module: "system.alert_log",
		ignore: "system.alert_log.alert.ignore",
		export: "system.alert_log.report.export",
		create: "system.alert_log.alert.create",
		update: "system.alert_log.alert.update",
		delete: "system.alert_log.alert.delete",
	},
	peopleCounting: {
		module: "system.people_counting",
		locationCreate: "system.people_counting.location.create",
		locationUpdate: "system.people_counting.location.update",
		locationDelete: "system.people_counting.location.delete",
		reportFull: "system.people_counting.report.full",
	},
	environment: {
		module: "system.environment",
		locationCreate: "system.environment.location.create",
		locationUpdate: "system.environment.location.update",
		locationDelete: "system.environment.location.delete",
		reportFull: "system.environment.report.full",
	},
	vehicleAccess: {
		module: "system.vehicle_access",
		locationCreate: "system.vehicle_access.location.create",
		locationUpdate: "system.vehicle_access.location.update",
		locationDelete: "system.vehicle_access.location.delete",
		plateManage: "system.vehicle_access.plate.manage",
		plateCreate: "system.vehicle_access.plate.create",
		plateUpdate: "system.vehicle_access.plate.update",
		plateDelete: "system.vehicle_access.plate.delete",
		reportFull: "system.vehicle_access.report.full",
		statisticsReset: "system.vehicle_access.statistics.reset",
		barrierControl: "system.vehicle_access.barrier.control",
	},
	videoSurveillance: {
		module: "system.video_surveillance",
		streamControl: "system.video_surveillance.stream.control",
	},
	areaPointMap: {
		module: "system.area_point_map",
		zoneDelete: "system.area_point_map.zone.delete",
		locationDelete: "system.area_point_map.location.delete",
	},
	elevator: {
		module: "system.elevator",
		locationCreate: "system.elevator.location.create",
		locationUpdate: "system.elevator.location.update",
		locationDelete: "system.elevator.location.delete",
		reportFull: "system.elevator.report.full",
		deviceControl: "system.elevator.device.control",
		floorManage: "system.elevator.floor.manage",
	},
	lighting: {
		module: "system.lighting",
		locationCreate: "system.lighting.location.create",
		locationUpdate: "system.lighting.location.update",
		locationDelete: "system.lighting.location.delete",
		deviceControl: "system.lighting.device.control",
	},
	hvac: {
		module: "system.hvac",
		locationCreate: "system.hvac.location.create",
		locationUpdate: "system.hvac.location.update",
		locationDelete: "system.hvac.location.delete",
		deviceControl: "system.hvac.device.control",
	},
	power: {
		module: "system.power",
		locationCreate: "system.power.location.create",
		locationUpdate: "system.power.location.update",
		locationDelete: "system.power.location.delete",
	},
	drainage: {
		module: "system.drainage",
		locationCreate: "system.drainage.location.create",
		locationUpdate: "system.drainage.location.update",
		locationDelete: "system.drainage.location.delete",
	},
	airCirculation: {
		module: "system.air_circulation",
		locationCreate: "system.air_circulation.location.create",
		locationUpdate: "system.air_circulation.location.update",
		locationDelete: "system.air_circulation.location.delete",
	},
	fire: {
		module: "system.fire",
		locationCreate: "system.fire.location.create",
		locationUpdate: "system.fire.location.update",
		locationDelete: "system.fire.location.delete",
	},
	emergencyRescue: {
		module: "system.emergency_rescue",
		locationCreate: "system.emergency_rescue.location.create",
		locationUpdate: "system.emergency_rescue.location.update",
		locationDelete: "system.emergency_rescue.location.delete",
	},
	smokeAlarm: {
		module: "system.smoke_alarm",
		locationCreate: "system.smoke_alarm.location.create",
		locationUpdate: "system.smoke_alarm.location.update",
		locationDelete: "system.smoke_alarm.location.delete",
	},
	multimedia: {
		module: "system.multimedia",
		settingsUpdate: "system.multimedia.settings.update",
	},
} as const

/** locationType（DB／API）→ 地點刪除權限碼；全區點位圖依系統刪除地點時使用 */
export const LOCATION_DELETE_BY_SYSTEM_TYPE: Record<string, string> = {
	people_counting: PERM.peopleCounting.locationDelete,
	environment: PERM.environment.locationDelete,
	vehicle_access: PERM.vehicleAccess.locationDelete,
	lighting: PERM.lighting.locationDelete,
	hvac: PERM.hvac.locationDelete,
	power: PERM.power.locationDelete,
	drainage: PERM.drainage.locationDelete,
	air_circulation: PERM.airCirculation.locationDelete,
	fire: PERM.fire.locationDelete,
	emergency_rescue: PERM.emergencyRescue.locationDelete,
	smoke_alarm: PERM.smokeAlarm.locationDelete,
	elevator: PERM.elevator.locationDelete,
}
