/**
 * 能源參數 catalog（前端 fallback + API）
 * SSOT：後端 energyParameterCatalog.js；GET /energy/parameters
 */

import type { SensorModbusDataType } from "~/types/device"

export type EnergyMeterKind = "electricity" | "water"
export type EnergyModbusDataType = SensorModbusDataType

export type EnergyParameterDef = {
	key: string
	label: string
	unit: string
	semantics: "cumulative" | "instantaneous"
	meterKinds: EnergyMeterKind[]
	fractionDigits: number
	sortOrder: number
	group?: string
}

export const ENERGY_PARAMETERS_FALLBACK: EnergyParameterDef[] = [
	{
		key: "active_energy",
		label: "輸入有效電能",
		unit: "kWh",
		semantics: "cumulative",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 10,
		group: "Energy",
	},
	{
		key: "total_energy",
		label: "總有效電能",
		unit: "kWh",
		semantics: "cumulative",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 11,
		group: "Energy",
	},
	{
		key: "export_energy",
		label: "輸出有效電能",
		unit: "kWh",
		semantics: "cumulative",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 12,
		group: "Energy",
	},
	{
		key: "water_volume",
		label: "累積水量",
		unit: "m³",
		semantics: "cumulative",
		meterKinds: ["water"],
		fractionDigits: 3,
		sortOrder: 20,
		group: "Energy",
	},
	{
		key: "active_power",
		label: "總有效功率",
		unit: "kW",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 2,
		sortOrder: 30,
		group: "Active_Power",
	},
	{
		key: "reactive_power",
		label: "總無功功率",
		unit: "kVAR",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 31,
		group: "Reactive_Power",
	},
	{
		key: "apparent_power",
		label: "總視在功率",
		unit: "kVA",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 32,
		group: "Apparent_Power",
	},
	{
		key: "demand",
		label: "需量",
		unit: "kW",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 2,
		sortOrder: 40,
		group: "Demand",
	},
	{
		key: "voltage_v1",
		label: "V1 相電壓",
		unit: "V",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 2,
		sortOrder: 100,
		group: "Voltage",
	},
	{
		key: "voltage_v2",
		label: "V2 相電壓",
		unit: "V",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 2,
		sortOrder: 101,
		group: "Voltage",
	},
	{
		key: "voltage_v3",
		label: "V3 相電壓",
		unit: "V",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 2,
		sortOrder: 102,
		group: "Voltage",
	},
	{
		key: "voltage_avg",
		label: "平均相電壓 VLN",
		unit: "V",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 2,
		sortOrder: 103,
		group: "Voltage",
	},
	{
		key: "current_i1",
		label: "I1 電流",
		unit: "A",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 110,
		group: "Current",
	},
	{
		key: "current_i2",
		label: "I2 電流",
		unit: "A",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 111,
		group: "Current",
	},
	{
		key: "current_i3",
		label: "I3 電流",
		unit: "A",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 112,
		group: "Current",
	},
	{
		key: "current_avg",
		label: "平均電流",
		unit: "A",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 113,
		group: "Current",
	},
	{
		key: "pf_1",
		label: "PF1 功率因數",
		unit: "--",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 120,
		group: "Power_Factor",
	},
	{
		key: "pf_2",
		label: "PF2 功率因數",
		unit: "--",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 121,
		group: "Power_Factor",
	},
	{
		key: "pf_3",
		label: "PF3 功率因數",
		unit: "--",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 122,
		group: "Power_Factor",
	},
	{
		key: "pf_avg",
		label: "平均功率因數",
		unit: "--",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 123,
		group: "Power_Factor",
	},
	{
		key: "active_power_p1",
		label: "P1 有效功率",
		unit: "kW",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 130,
		group: "Active_Power",
	},
	{
		key: "active_power_p2",
		label: "P2 有效功率",
		unit: "kW",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 131,
		group: "Active_Power",
	},
	{
		key: "active_power_p3",
		label: "P3 有效功率",
		unit: "kW",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 132,
		group: "Active_Power",
	},
	{
		key: "frequency",
		label: "頻率",
		unit: "Hz",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 140,
		group: "Item",
	},
	{
		key: "load_type",
		label: "負載特性",
		unit: "--",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 0,
		sortOrder: 141,
		group: "Item",
	},
	{
		key: "run_hour",
		label: "操作時間",
		unit: "min",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 0,
		sortOrder: 142,
		group: "Item",
	},
	{
		key: "co2",
		label: "CO2 排放",
		unit: "Kg",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 3,
		sortOrder: 143,
		group: "Item",
	},
	{
		key: "cost",
		label: "電費金額",
		unit: "--",
		semantics: "instantaneous",
		meterKinds: ["electricity"],
		fractionDigits: 2,
		sortOrder: 144,
		group: "Item",
	},
]

export const ENERGY_DATA_TYPE_OPTIONS: Array<{ value: EnergyModbusDataType; label: string }> = [
	{ value: "uint16", label: "uint16（1 暫存器）" },
	{ value: "uint32_be", label: "uint32 大端（2 暫存器）" },
	{ value: "uint32_le", label: "uint32 小端（2 暫存器）" },
	{ value: "float32_be", label: "float32 大端（2 暫存器）" },
	{ value: "float32_le", label: "float32 小端（2 暫存器）" },
	{ value: "float64_be", label: "float64 大端（4 暫存器）" },
	{ value: "float64_le", label: "float64 小端（4 暫存器）" },
]

export const lengthFromEnergyDataType = (dataType: string | undefined): number => {
	const t = String(dataType || "uint16")
	if (t === "uint16") return 1
	if (t === "float64_be" || t === "float64_le") return 4
	return 2
}

export const ENERGY_METER_KIND_OPTIONS: Array<{ value: EnergyMeterKind | ""; label: string }> = [
	{ value: "", label: "一般感測器（無表計種類）" },
	{ value: "electricity", label: "數位電表" },
	{ value: "water", label: "數位水表" },
]
