/**
 * 環境參數 catalog fallback（離線／API 失敗時）
 * SSOT：ba-backend/src/constants/environmentParameterCatalog.js
 */
import type { EnvironmentParametersResponse } from "~/types/environmentCatalog"

export const ENVIRONMENT_PARAMETERS_FALLBACK: EnvironmentParametersResponse = {
	version: "2026-07-17",
	sensorKeys: [
		"pm25",
		"pm10",
		"tvoc",
		"hcho",
		"humidity",
		"temperature",
		"co2",
		"noise",
		"wind",
	],
	derivedKeys: ["aqi", "heatIndex"],
	parameters: [
		{
			key: "pm25",
			kind: "sensor",
			label: "PM2.5",
			unit: "µg/m³",
			fractionDigits: 0,
			gaugeMax: 150,
			icon: "/environment/PM2.5.png",
			sortOrder: 10,
			capabilities: { deviceModel: true, locationToggle: true, alertThreshold: true },
		},
		{
			key: "pm10",
			kind: "sensor",
			label: "PM10",
			unit: "µg/m³",
			fractionDigits: 0,
			gaugeMax: 150,
			icon: "/environment/PM10.png",
			sortOrder: 20,
			capabilities: { deviceModel: true, locationToggle: true, alertThreshold: true },
		},
		{
			key: "tvoc",
			kind: "sensor",
			label: "TVOC",
			unit: "ppm",
			fractionDigits: 1,
			gaugeMax: 10,
			icon: "/environment/TVOC.png",
			sortOrder: 30,
			capabilities: { deviceModel: true, locationToggle: true, alertThreshold: true },
		},
		{
			key: "hcho",
			kind: "sensor",
			label: "HCHO",
			unit: "ppm",
			fractionDigits: 1,
			gaugeMax: 1,
			icon: "/environment/HCHO.png",
			sortOrder: 40,
			capabilities: { deviceModel: true, locationToggle: true, alertThreshold: true },
		},
		{
			key: "humidity",
			kind: "sensor",
			label: "濕度",
			unit: "%",
			fractionDigits: 1,
			gaugeMax: 100,
			icon: "/environment/humidity.png",
			sortOrder: 50,
			capabilities: { deviceModel: true, locationToggle: true, alertThreshold: true },
		},
		{
			key: "temperature",
			kind: "sensor",
			label: "溫度",
			unit: "°C",
			fractionDigits: 1,
			gaugeMax: 50,
			icon: "/environment/temperature.png",
			sortOrder: 60,
			capabilities: { deviceModel: true, locationToggle: true, alertThreshold: true },
		},
		{
			key: "co2",
			kind: "sensor",
			label: "CO2",
			unit: "ppm",
			fractionDigits: 0,
			gaugeMax: 2000,
			icon: "/environment/CO2.png",
			sortOrder: 70,
			capabilities: { deviceModel: true, locationToggle: true, alertThreshold: true },
		},
		{
			key: "noise",
			kind: "sensor",
			label: "噪音值",
			unit: "dB",
			fractionDigits: 0,
			gaugeMax: 100,
			icon: "/environment/noise.png",
			sortOrder: 80,
			capabilities: { deviceModel: true, locationToggle: true, alertThreshold: true },
		},
		{
			key: "wind",
			kind: "sensor",
			label: "風速",
			unit: "m/s",
			fractionDigits: 1,
			gaugeMax: 30,
			icon: "/environment/wind-speed.png",
			sortOrder: 90,
			capabilities: { deviceModel: true, locationToggle: true, alertThreshold: true },
		},
		{
			key: "aqi",
			kind: "derived",
			label: "AQI",
			unit: "",
			fractionDigits: 0,
			gaugeMax: 150,
			sortOrder: 100,
			capabilities: { deviceModel: false, locationToggle: false, alertThreshold: false },
			display: {
				statusBands: [
					{ max: 100, status: "normal" },
					{ max: 150, status: "warning" },
					{ max: null, status: "alarm" },
				],
			},
		},
		{
			key: "heatIndex",
			kind: "derived",
			label: "熱指數",
			unit: "°C",
			fractionDigits: 1,
			gaugeMax: null,
			sortOrder: 110,
			capabilities: { deviceModel: false, locationToggle: false, alertThreshold: false },
			display: {
				levelBands: [
					{ max: 27, level: 1 },
					{ max: 32, level: 2 },
					{ max: 41, level: 3 },
					{ max: 54, level: 4 },
					{ max: null, level: 5 },
				],
				levelUnitLabel: "級",
			},
		},
	],
	thresholdOperators: [
		{ op: ">", label: "超過" },
		{ op: ">=", label: "超過" },
		{ op: "<", label: "低於" },
		{ op: "<=", label: "低於" },
	],
}
